/* auto-generated by NAPI-RS */
/* eslint-disable */

/** Mouse button or wheel direction accepted by mouseClick / mouseDown / mouseUp */
export type MouseButton =
  | 'left'
  | 'right'
  | 'middle'
  | 'scrollUp'
  | 'scrollDown'
  | 'scrollLeft'
  | 'scrollRight'

/** Physical key name accepted by keyTap / keyDown / keyUp (layout-independent) */
export type KeyboardKey =
  | 'a'
  | 'b'
  | 'c'
  | 'd'
  | 'e'
  | 'f'
  | 'g'
  | 'h'
  | 'i'
  | 'j'
  | 'k'
  | 'l'
  | 'm'
  | 'n'
  | 'o'
  | 'p'
  | 'q'
  | 'r'
  | 's'
  | 't'
  | 'u'
  | 'v'
  | 'w'
  | 'x'
  | 'y'
  | 'z'
  | '0'
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | 'f1'
  | 'f2'
  | 'f3'
  | 'f4'
  | 'f5'
  | 'f6'
  | 'f7'
  | 'f8'
  | 'f9'
  | 'f10'
  | 'f11'
  | 'f12'
  | 'f13'
  | 'f14'
  | 'f15'
  | 'f16'
  | 'f17'
  | 'f18'
  | 'f19'
  | 'f20'
  | 'enter'
  | 'escape'
  | 'backspace'
  | 'delete'
  | 'tab'
  | 'space'
  | 'up'
  | 'down'
  | 'left'
  | 'right'
  | 'home'
  | 'end'
  | 'pageUp'
  | 'pageDown'
  | 'capsLock'
  | 'control'
  | 'shift'
  | 'alt'
  | 'meta'
  | 'rcontrol'
  | 'rshift'
  | 'ralt'
  | 'rmeta'
  | 'numpad0'
  | 'numpad1'
  | 'numpad2'
  | 'numpad3'
  | 'numpad4'
  | 'numpad5'
  | 'numpad6'
  | 'numpad7'
  | 'numpad8'
  | 'numpad9'
export declare function getMousePos(): MousePosition | null

export declare function keyDown(key: KeyboardKey, modifier?: Array<string> | undefined | null): void

export declare function keyTap(key: KeyboardKey, modifier?: Array<string> | undefined | null): void

export declare function keyToggle(key: KeyboardKey, down: string, modifier?: Array<string> | undefined | null): void

export declare function keyUp(key: KeyboardKey, modifier?: Array<string> | undefined | null): void

export declare function mouseClick(button: MouseButton): void

export declare function mouseDoubleClick(button: MouseButton): void

export declare function mouseDown(button: MouseButton): void

export declare function mouseDrag(x: number, y: number): void

/** Mouse position */
export interface MousePosition {
  x: number
  y: number
}

export declare function mouseScroll(length: number, isVertical: boolean): void

export declare function mouseScrollXy(x: number, y: number): void

export declare function mouseUp(button: MouseButton): void

export declare function moveMouseAbs(x: number, y: number): void

export declare function moveMouseRel(x: number, y: number): void

export declare function moveMouseSmooth(x: number, y: number): void

export declare function moveMouseSmoothWithSpeed(x: number, y: number, speed: number): void

export declare function typeText(text: string): void

export declare function typeTextDelayed(text: string, cpm: number): void

export declare function unicodeTap(ch: string): void
